baseURL = "https://dsml.cs12.ir"
languageCode = "fa-ir"
# بهتره که به این شکل باشه : اسم مبحث + به سبک تِرِد 
# مثلا : شبکه به سبک تِرِد
title = "دیتا ساینس به سبک تِرِد"

# ===========================================
# تنظیمات کلی سایت
# ===========================================

[params]
# توضیح کوتاه برای کل سایت بیشتر بدرد seo میخوره
description = "آموزش دیتا ساینس و ماشین لرنینگ برای تنبل ها"
threads_preview_count = 3
threads_chap_count_per_page = 2

[params.banner]
# مثلا سیستم عامل یا شبکه
subject = "دیتا ساینس"

# ===========================================
# تنظیمات دارک مود
# enabled = true: دکمه تغییر تم نمایش داده میشه
# enabled = false: دکمه تغییر تم مخفیه (حالت پیش‌فرض)
# فعلا اینیبل نکنید...
# ===========================================

[params.dark_mode]
enabled = false

# ===========================================
# متن لایسنس پیش‌فرض مطالب
# این متن توی صفحه تکی هر ترد نمایش داده میشه
# کاراکتر {license} با مقدار license از frontmatter جایگزین میشه
# ===========================================

[params.license]
text = " مگه میشه مطلبی بدون لایسنس آخه؟ لایسنس این مطلب : {license}"

# ===========================================
# اطلاعات نویسنده اصلی سایت
# ===========================================

[params.author]
name = "علیرضاعابدینی"
# بیوگرافی کوتاه نویسنده که زیر اسمش نمایش داده میشه
bio = "علاقه‌مند به علوم کامپیوتر و معمار سیستم ها، با تمرکز بر بهینه‌ سازی، روش‌ های ابتکاری (Heuristics) و سیستم های یادگیر. مفاهیم را از اصول بنیادین مطالعه می‌ کنم و بر دقت ریاضی و اثبات‌ های سازنده تأکید دارم؛ زیرا معتقدم درک عمیق هر مفهوم باید بر پیاده‌ سازی آن مقدم باشد.
زمینه‌های مورد علاقه:
- یادگیری ماشین (Machine Learning)
- مهندسی ویژگی (Feature Engineering)
- بینایی ماشین (Computer Vision)
- مدل های زبانی (Language Modeling)
- مدل‌ های محاسباتی تطبیقی که پلی میان مبانی نظری و سامانه‌ های مهندسی‌شده ایجاد می‌ کنند."
# آدرس عکس پروفایل نویسنده 
avatar = "/assets/static-pic/avatar.jpg"
# لینک صفحه دونیت یا حمایت مالی
donate_url = "#"

# ===========================================
# لینک‌های شبکه‌های اجتماعی نویسنده (اختیاری)
# این لینک‌ها در پروفایل نویسنده نمایش داده میشن
# ===========================================

[params.author.social]
# لیست لینک‌های شبکه‌های اجتماعی
# هر آیتم شامل name و url هست
# مثال: {name = "github", url = "https://github.com/user"}

social_links = [
  {name = "گیت هابم", url = "https://github.com/DoCTheBest01"},
]

# ===========================================
# متن‌های مدال (پنجره‌های بازشونده)
# این متن‌ها وقتی کاربر روی آیکون‌ها کلیک میکنه نمایش داده میشن
# ===========================================

[params.modal]
# متن عنوان مدال وقتی هنوز تردی منتشر نشده
empty_title = "هنوز هیچ تردی منتشر نشده!"
# متن توضیحات مدال وقتی هنوز تردی منتشر نشده
empty_text = "از یکشنبه اولین تردها رو شروع میکنم. پس فعلاً فقط آماده باش :)"
# متن دکمه کپی لینک در مدال اشتراک‌گذاری
copy_link_text = "کپی لینک"
# متن بعد از کپی شدن لینک
copied_text = "کپی شد"

# ===========================================
# متن‌های مرتبط با ترد (پست‌ها)
# این متن‌ها توی صفحه تکی ترد و لیست تردها استفاده میشن
# ===========================================

[params.thread]
# متنی که بعد از خوندن یک ترد نمایش داده میشه
read_message = "شما این تِرِد رو مطالعه کردید آفرین.🍻"
# متن دکمه "خواندی؟ کلیک کن"
mark_read_text = "خوندی؟ کلیک کن"
# متن دکمه بعد از کلیک (یعنی ترد خوانده شده)
marked_read_text = "خونده نشده"
# متن عنوان مدال تبریک بعد از خوندن ترد
congrats_title = "تبریک عرض مینمایم"
# متن مدال تبریک (کاراکتر {count} با تعداد تردهای خوانده شده جایگزین میشه)
congrats_text = "تا الان {count} ترد خوندی بنازمتتتت"
# متن اشتراک‌گذاری (کاراکتر {title} با عنوان ترد جایگزین میشه)
share_text = "سلام دوستان! ترد '{title}' رو بخونید، خیلی مفیده"
# تعداد ترد در هر صفحه مربوط به اون فصل مثلا : /threads/chapter1
threads_per_page = 5
# آدرس عکس تبریک (بعد از خوندن ترد)
congrats_image = "/assets/static-pic/congrat.gif"

# ===========================================
# دست نزن به این بخش برادر من خب...
# ===========================================

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# ===========================================
# تنظیمات گیت‌هاب
# برای لینک‌های "ویرایش در گیت‌هاب" و "مشاهده منبع" استفاده میشه
# ===========================================

[params.github]
# آدرس ریپو گیت هابتون رو این شکلی بزارید :  username/repo-name
repo = "The-CS12/dsml-course"
# برنچ اصلی رو هم بزارید...
branch = "content"

# ===========================================
# تنظیمات سیستم نظرات
# برای فعال‌سازی، اول باید گیسکاس رو در گیت‌هاب فعال کنید
# به سایت زیر برید و مرحله به مرحله کارایی که گفته رو انجام بدید تا اسکریپت مورد نظر رو بهتون بده
# https://giscus.app
# ===========================================

[params.giscus]
# اسکریپتی که از giscus گرفتید رو اینجا پیست کنید
script = '''

<script src="https://giscus.app/client.js"
        data-repo="The-CS12/dsml-course"
        data-repo-id="R_kgDOTG0qwQ"
        data-category="General"
        data-category-id="DIC_kwDOTG0qwc4DAAMN"
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light"
        data-lang="fa"
        crossorigin="anonymous"
        async>
</script>

'''

